server:
    application:
        name: test-service
    port: 9000 #指定启动端口号
    servlet:
        context-path: /Shopping
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations: classpath*:com/flight/china/mapper/**.xml    #把xml文件放在com.XX.mapper.*中可能会出现找不到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.flight.china.bean        #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false     

##logging:
##  file: test-service.log
##  level:
##    com.flight.china.dao: debug
    
    
